global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: backend_service
    metrics_path: /api/metrics
    static_configs:
      - targets: ['back:80']
      
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
          

